# Generated by Django 5.0.3 on 2024-03-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200)),
                ('pname', models.CharField(max_length=200)),
                ('pprice', models.CharField(max_length=200)),
            ],
        ),
    ]
