# Generated by Django 5.0.3 on 2024-03-23 04:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('87b0e2d5-b6c2-4568-a953-ebcdf80fbc0d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
