# Generated by Django 5.0.3 on 2024-03-23 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e8ca5811-652c-4a5e-91ee-180563d68e39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
