# Generated by Django 5.0.3 on 2024-03-23 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e9311be4-6c51-4851-87f2-2da3a19777c8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
