# Generated by Django 5.0.3 on 2024-03-23 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_todo_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('dis', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4655db46-95f7-463e-9185-a94bbef2e3e5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
